---
# This playbook provisions a node to build Dogtag PKI

- name: Load all roles
  hosts: ipa
  remote_user: root
  roles:
     - dev_env
     - build_jss
     - install_jss
     - build_tomcatjss
     - install_tomcatjss
     - build_pki
     - install_pki
     - install_ipa
     - configure_ipa
