## Role choices:
# - client
# - replica
# - replica_finish
# - master
# - master_add_replica
role: master
hostname: ipa
address: 192.168.122.160
master_hostname: ipa
master_address: 192.168.122.160
replica_hostname: ipa-replica
replica_address: 192.168.122.242
domain: cipherdev.io
realm: CIPHERDEV.IO
password: Secret.123
forwarder: 192.168.1.1
