---
# This playbook installs PKI copr from a built image.

- name: Install dnf-plugins-core
  shell: dnf install -y dnf-plugins-core

- name: Enable the PKI copr repo
  shell: dnf copr enable -y "@pki/{{ copr_version }}"

- name: Refresh repositories
  shell: dnf update --refresh --assumeno || true
