---
# This role configures the installation of an IPA master

- name: kinit to admin
  shell: echo "{{ password }}" | kinit "admin@{{ realm|upper }}"
  ignore_errors: yes

- name: Uninstall IPA Server
  shell: ipa-server-install --uninstall -U -v
  when: role == "master"
