---
# This role configures the installation of a dogtag PKI master

- name: Copy KRA RSA configuration
  copy:
    src: KRA-RSA.cfg
    dest: /root/kra.cfg
    owner: root
    group: root
    mode: 0644
  when: pki_type == 'RSA'

- name: Copy KRA EC configuration
  copy:
    src: KRA-EC.cfg
    dest: /root/kra.cfg
    owner: root
    group: root
    mode: 0644
  when: pki_type == 'EC'

- name: Replace with hostname
  shell: sed "s/\$HOSTNAME/$(hostname)/" -i /root/kra.cfg

- name: Spawn KRA
  shell: pkispawn -f /root/kra.cfg -s KRA
