---
# This role configures the installation of a dogtag PKI master

- name: Copy CA RSA configuration
  copy:
    src: CA-RSA.cfg
    dest: /root/ca.cfg
    owner: root
    group: root
    mode: 0644
  when: pki_type == 'RSA'

- name: Copy CA EC configuration
  copy:
    src: CA-EC.cfg
    dest: /root/ca.cfg
    owner: root
    group: root
    mode: 0644
  when: pki_type == 'EC'

- name: Spawn CA
  shell: pkispawn -f /root/ca.cfg -s CA
