---
# This playbook builds JSS from the specified git repository
#
# To define which git repository, see the vars in roles/jss/vars/main.yml

- name: Install JSS dependencies
  dnf:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
     - apache-commons-lang
     - apache-commons-codec
     - gcc-c++
     - git
     - make
     - mercurial
     - nspr-devel
     - nss-devel
     - java-devel
     - jpackage-utils
     - rpm-build
     - slf4j
     - slf4j-jdk14
     - zlib-devel

- name: Create jss user
  user:
    name: jss
    shell: /bin/bash
    generate_ssh_key: yes

- name: Set up jss git name
  command: git config --global user.name jss
  become: yes
  become_user: jss

- name: Set up jss git email
  command: git config --global user.email jss@github.com
  become: yes
  become_user: jss

- name: Remove sandbox directory
  file:
    path: /home/jss/sandbox
    state: absent
    force: yes

- name: Remove build directory
  file:
    path: /home/jss/build
    state: absent
    force: yes

- name: Create sandbox directory
  file:
    path: /home/jss/sandbox
    state: directory
    owner: jss
    group: jss

- name: Clone nspr repository
  hg:
    repo: https://hg.mozilla.org/projects/nspr
    clone: yes
    update: yes
    dest: /home/jss/sandbox/nspr
  become: yes
  become_user: jss
  when: not build_rpm

- name: Clone nss repository
  hg:
    repo: https://hg.mozilla.org/projects/nss
    clone: yes
    update: yes
    dest: /home/jss/sandbox/nss
  become: yes
  become_user: jss
  when: not build_rpm

- name: Clone jss repository
  git:
    repo: "{{ origin_url }}"
    clone: yes
    update: yes
    dest: /home/jss/sandbox/jss
    version: "{{ origin_branch }}"
  become: yes
  become_user: jss

- name: Add jss upstream
  command: "git remote add upstream {{ upstream_url }}"
  args:
    chdir: /home/jss/sandbox/jss
  become: yes
  become_user: jss

- name: Update from upstream
  command: git fetch upstream
  args:
    chdir: /home/jss/sandbox/jss
  become: yes
  become_user: jss

- name: Rebase against upstream
  command: "git rebase upstream/{{ upstream_branch }}"
  args:
    chdir: /home/jss/sandbox/jss
  become: yes
  become_user: jss

- name: Checkout upstream master
  command: "git checkout upstream/master"
  args:
    chdir: /home/jss/sandbox/jss
  become: yes
  become_user: jss
  when: not build_rpm

- name: Install dependencies
  command: "dnf builddep -y jss.spec"
  args:
    chdir: /home/jss/sandbox/jss

- name: Clean, build, and test jss on master (first)
  shell: make clean all test_jss >/home/jss/jss_first_build.out 2>&1
  args:
    chdir: /home/jss/sandbox/jss
  become: yes
  become_user: jss
  environment:
    - JAVA_HOME: /etc/alternatives/java_sdk_openjdk
    - USE_64: 1
  when: not build_rpm

- name: Clean, build, and test jss on master (real)
  shell: make clean all test_jss >/home/jss/jss_master_build.out 2>&1
  args:
    chdir: /home/jss/sandbox/jss
  become: yes
  become_user: jss
  environment:
    - JAVA_HOME: /etc/alternatives/java_sdk_openjdk
    - USE_64: 1
  when: not build_rpm

- name: Checkout branch
  command: "git checkout {{ origin_branch }}"
  args:
    chdir: /home/jss/sandbox/jss
  become: yes
  become_user: jss
  when: not build_rpm


- name: Clean, build, and test jss on branch
  shell: make clean all test_jss >/home/jss/jss_branch_build.out 2>&1
  args:
    chdir: /home/jss/sandbox/jss
  become: yes
  become_user: jss
  environment:
    - JAVA_HOME: /etc/alternatives/java_sdk_openjdk
    - USE_64: 1
  when: not build_rpm

- name: Build RPM
  shell: ./build.sh
  args:
    chdir: /home/jss/sandbox/jss
  become: yes
  become_user: jss
  environment:
    - JAVA_HOME: /etc/alternatives/java_sdk_openjdk
    - USE_64: 1
  when: build_rpm
