pki:
  origin:
    url: https://github.com/cipherboy/pki
    branch: pki-jss-imports-unsync
  upstream:
    url: https://github.com/dogtagpki/pki
    branch: master
  build:
    rpm: true
    version: "10.6"
