---
# This role configures the installation of an IPA master

- name: Set IPA hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ hostname }}.{{ domain }}"
    regexp: '(\s)*{{ ansible_default_ipv4.address }}(\s)*{{ hostname }}.{{ domain }}(\s)*'
  when: role == "master" or role == "client" or role == "replica"

- name: Set IPA master hostname in /etc/hosts on client/replica
  lineinfile:
    path: /etc/hosts
    line: "{{ master_address }} {{ master_hostname }}.{{ domain }}"
    regexp: '(\s)*{{ master_address }}(\s)*{{ master_hostname }}.{{ domain }}(\s)*'
  when: role == "client" or role == "replica"

- name: Set IPA replica hostname in /etc/hosts on master
  lineinfile:
    path: /etc/hosts
    line: "{{ replica_address }} {{ replica_hostname }}.{{ domain }}"
    regexp: '(\s)*{{ replica_address }}(\s)*{{ replica_hostname }}.{{ domain }}(\s)*'
  when: role == "master_add_replica"

- name: Set IPA hostname via hostnamectl
  hostname:
    name: "{{ hostname }}.{{ domain }}"
  when: role == "master" or role == "client" or role == "replica"

- name: Reboot after setting hostname
  reboot:
  when: role == "master" or role == "client" or role == "replica"

- name: Install IPA Server Master
  shell: ipa-server-install -U -r "{{ realm|upper }}" -n "{{ domain }}" -p "{{ password }}" -a "{{ password }}" "--hostname={{ hostname }}.{{ domain }}" --setup-kra
  when: role == "master"

- name: Install IPA Client
  shell: ipa-client-install -U "--domain={{ domain }}" "--realm={{ realm|upper }}" "--server={{ master_hostname }}.{{ domain }}" -w "{{ password }}" "--principal=admin@{{ realm|upper }}"
  when: role == "client" or role == "replica"

- name: kinit to admin
  shell: echo "{{ password }}" | kinit "admin@{{ realm|upper }}"
  when: role == "replica" or role == "master" or role == "master_add_replica"

- name: Add IPA replica to master
  shell: ipa hostgroup-add-member ipaservers --hosts "{{ replica_hostname }}.{{ domain }}"
  when: role == "master_add_replica"

- name: Install IPA Replica
  shell: ipa-replica-install
  when: role == "replica_finish"
