---
# Creates a development environment

- name: Update system time
  shell: chronyc makestep

- name: Run DNF updates
  shell: dnf update --refresh -y

- name: Do something stupid
  shell: (rm -f /usr/bin/python || true) && ln -s /usr/bin/python3 /usr/bin/python
  when: ansible_distribution == 'Fedora' and ansible_distribution_version == '30'

- name: Install useful packages
  dnf:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
     # - ccache
     - cmake
     - gdb
     - git
     - libselinux-python3
     - make
     # - nmap
     - rpm-build
     # - screen
     - tmux
     - vim-enhanced

- name: Install jedi-vim
  shell: dnf install -y vim-jedi ccache nmap screen
  when: ansible_distribution == 'Fedora'

#- name: Disable firewalld
#  systemd:
#    name: firewalld
#    state: stopped
#    enabled: no

- name: Flush iptables
  shell: iptables -F

- name: Install dotfiles
  shell: curl -sSL https://df.cipherboy.com/ | bash
