---
# Creates a development environment

- name: Install useful packages
  dnf:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
     - ccache
     - cmake
     - gdb
     - git
     - make
     - rpm-build
     - screen
     - tmux
     - vim-enhanced
