---
# Creates a development environment

- name: Run DNF updates
  shell: dnf update --refresh -y

- name: Install useful packages
  dnf:
    name: "{{ packages }}"
    state: installed
  vars:
    packages:
     - ccache
     - cmake
     - gdb
     - git
     - libselinux-python
     - make
     - nmap
     - rpm-build
     - screen
     - tmux
     - vim-enhanced

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Flush iptables
  shell: iptables -F

- name: Install dotfiles
  shell: curl https://cipherboy.com/s/dotfiles.sh | bash
