---
# This playbook builds JSS from the specified git repository
#
# To define which git repository, see the vars in roles/build_pki/vars/main.yml

#- name: Install PKI dependencies
#  command: dnf build-dep "pki-*" -y

- name: Create pki user
  user:
    name: pki
    shell: /bin/bash
    generate_ssh_key: yes

- name: Set up pki git name
  command: git config --global user.name pki
  args:
    chdir: /home/pki
  become: yes
  become_user: pki

- name: Set up pki git email
  command: git config --global user.email pki@github.com
  args:
    chdir: /home/pki
  become: yes
  become_user: pki

- name: Remove sandbox directory
  file:
    path: /home/pki/sandbox
    state: absent
    force: yes

- name: Remove build directory
  file:
    path: /home/pki/build
    state: absent
    force: yes

- name: Create sandbox directory
  file:
    path: /home/pki/sandbox
    state: directory
    owner: pki
    group: pki

- name: Clone pki repository
  git:
    repo: "{{ origin_url }}"
    clone: yes
    update: yes
    dest: /home/pki/sandbox/pki
    version: "{{ origin_branch }}"
  become: yes
  become_user: pki

- name: Add pki upstream
  command: "git remote add upstream {{ upstream_url }}"
  args:
    chdir: /home/pki/sandbox/pki
  become: yes
  become_user: pki

- name: Update from upstream
  command: git fetch upstream
  args:
    chdir: /home/pki/sandbox/pki
  become: yes
  become_user: pki

- name: Rebase against upstream
  command: "git rebase upstream/{{ upstream_branch }}"
  args:
    chdir: /home/pki/sandbox/pki
  become: yes
  become_user: pki

- name: Install additional PKI dependencies
  command: dnf build-dep --spec pki.spec -y
  args:
    chdir: /home/pki/sandbox/pki
  when: build_version == "10.6" or build_version == "10.7"

- name: Build RPM for 10.5
  shell: ./scripts/compose_pki_core_packages rpms
  args:
    chdir: /home/pki/sandbox/pki
  become: yes
  become_user: pki
  when: build_rpm and build_version == "10.5"

- name: Build RPM for 10.6
  shell: bash build.sh
  args:
    chdir: /home/pki/sandbox/pki
  become: yes
  become_user: pki
  when: build_rpm and (build_version == "10.6" or build_version == "10.7")
